# Generated by Django 3.1.14 on 2023-12-23 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elastic', '0002_auto_20231222_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishDate',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
