# Generated by Django 5.0 on 2024-01-01 12:32

import datetime
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Mod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=150,
                        unique=True,
                        validators=[
                            django.core.validators.EmailValidator(
                                message="Enter a valid email address."
                            )
                        ],
                    ),
                ),
                ("username", models.CharField(max_length=50, unique=True)),
                ("password", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TokenAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 1, 1, 12, 32, 2, 263774, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "admin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warafi.admin"
                    ),
                ),
            ],
            options={"unique_together": {("admin", "token")},},
        ),
        migrations.CreateModel(
            name="TokenMod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 1, 1, 12, 32, 2, 263774, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "mod",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warafi.mod"
                    ),
                ),
            ],
            options={"unique_together": {("mod", "token")},},
        ),
        migrations.CreateModel(
            name="TokenUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token", models.CharField(max_length=300)),
                (
                    "created_at",
                    models.DateTimeField(
                        default=datetime.datetime(
                            2024, 1, 1, 12, 32, 2, 264774, tzinfo=datetime.timezone.utc
                        )
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warafi.user"
                    ),
                ),
            ],
            options={"unique_together": {("user", "token")},},
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("article_id", models.IntegerField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="warafi.user"
                    ),
                ),
            ],
            options={"unique_together": {("user", "article_id")},},
        ),
    ]
