# Generated by Django 5.0 on 2024-01-01 23:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warafi', '0003_alter_tokenadmin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 23, 16, 41, 506137, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokenmod',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 23, 16, 41, 507136, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokenuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 1, 23, 16, 41, 507136, tzinfo=datetime.timezone.utc)),
        ),
    ]
