# Generated by Django 5.0 on 2024-01-02 21:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warafi', '0004_alter_tokenadmin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokenadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 21, 49, 2, 959576, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokenmod',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 21, 49, 2, 959576, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokenuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 2, 21, 49, 2, 960594, tzinfo=datetime.timezone.utc)),
        ),
    ]
