# Generated by Django 5.0 on 2024-01-07 23:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warafi', '0005_alter_tokenadmin_created_at_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='user',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='favorite',
            name='article_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='tokenadmin',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 23, 48, 34, 350589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokenmod',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 23, 48, 34, 350589, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='tokenuser',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 23, 48, 34, 350589, tzinfo=datetime.timezone.utc)),
        ),
    ]
